name: Discord message
on:
  push: # github.event_name == push
  pull_request: # github.event_name == pull_request
    types:
      - merged
      - open # needed?
      - closed
      - reopened
      - edited
  pull_request_review:
    types: [edited, dismissed]

  issue_comment: # github.event_name == issue_comment
        
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
#    - name: Checkout repository
 #     uses: actions/checkout@v1
    - name: Event name
      run: echo "Event name ${{ github.event_name }}"
    - name: if Pull_request
      if: ${{ github.event_name =='pull_request' }}
      run: echo "Event action ${{ github.event.action }}."
    - name: if Issue Comment   
      if: ${{ github.event_name =='issue_comment' }}
      run: echo "Event action ${{ github.event.action }}."
    - name: if Push   
      if: ${{ github.event_name =='push' }}
      run: echo "I am push ."
    - name: if Review   
      if: ${{ github.event_name =='pull_request_review' }}
      run: echo "Event action ${{ github.event.action }}."
      

#    - name: Run Discord Webhook
#     # if: ${{ github.event.issue.name =='pull_request' }}  #github.event_name == 'pull_request' || 
#      uses: Mist3r-Robot/classic-discord-webhook@master
#      with:
#        id: ${{ secrets.DISCORD_WEBHOOK_ID }}
#        token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
 